repos:

-   repo: https://github.com/adamchainz/django-upgrade
    rev: "1.25.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff-check
        name: ruff check
        args: ["--fix"]
    -   id: ruff-format
        name: ruff format
