language: python
python:
  - "3.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.11
services:
  - mysql
  - postgresql
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=1.9
    - python: "2.7"
      env: DJANGO_VERSION=1.10
      
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - mysql -e 'create database django_prometheus_1;'
before_script:
  - pep8 .
script:
  - python setup.py test
  - (cd django_prometheus/tests/end2end; PYTHONPATH=../../.. python manage.py test)
