line-length = 120
target-version = "py39"

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    # https://github.com/PyCQA/flake8-bugbear
    "B",
    # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    # https://github.com/adamchainz/flake8-comprehensions
    "C4",
    # https://docs.astral.sh/ruff/rules/#error-e
    # https://github.com/PyCQA/pycodestyle
    "E",
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    # https://github.com/PyCQA/pyflakes
    "F",
    # https://docs.astral.sh/ruff/rules/#isort-i
    # https://pycqa.github.io/isort/
    "I",
    # https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    # https://github.com/jbkahn/flake8-debugger
    "T10",
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    # https://github.com/asottile/pyupgrade
    "UP",
    # https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
    # https://github.com/asottile-archive/flake8-2020
    "YTT",
    # https://docs.astral.sh/ruff/rules/#warning-w
    # https://github.com/PyCQA/pycodestyle
    "W",
]
